services:
  flask:
    container_name: rds-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - rds_data:/api/data
    cpus: '0.50'
    mem_limit: 200M
    pids_limit: 50
    restart: unless-stopped

volumes:
  rds_data:
    driver: local
